
## INIFILEVERSION #############################################################

[INIFILEVERSION]
VERSION		= 200
USERCFG		= No

## GLOBAL #####################################################################

[GLOBAL]
LANGUAGE	= us
LICENSENUM	= DEMO-DEMO-00-DEMO-00
LASTLANGUAGE	= us
NCASSISTWIDTH	= 232
ASSISTBALLOON	= Yes
MALLOW		= No
VERSION		= 51175
COMPANYNAME	= TEAM NULL
TYPESDIR	= 

## SYSTEM #####################################################################

[SYSTEM]
DISABLEBACKPLOT	= No
DISABLENCBASE	= Yes
DISABLEDNCADM	= Yes
DISABLEMINICAD	= No
DISABLESOLID	= No
RECENTLISTSIZE	= 16
RECENTLISTSHORTS= No
WARNINGBEEP	= Yes
STARTMAX	= Yes
REOPEN		= No
REMEMBERWINPOS	= Yes
PROTECTREAD	= Yes
OPENMAX		= Yes
REMEMBERCURSOR	= Yes
CONFIRMEXIT	= No
OPENMULTI	= No
CHECKMODIFIED	= Yes
KEEPBACKUP	= No
PATHINTITLE	= Yes
SPECIFYNAME	= No
SHOWALLFILES	= No
DISABLEFILECOMP	= No
DISABLEMATHFUNC	= No
DISABLEANIMATE	= No
DISABLEDNC	= No
NLINSIZE	= 2
CHECKMODTIME	= 1
SHOWSIZE	= 0
PASSWORD	= 
TABCHARS	= 8

## LASTSYSTEM #################################################################

[LASTSYSTEM]
DISABLENCBASE	= Yes
DISABLEDNCADM	= Yes
DISABLEBACKPLOT	= No
DISABLEFILECOMP	= No
DISABLEMATHFUNC	= No
DISABLEDNC	= No
DISABLEMINICAD	= No
DISABLESOLID	= No

## EDITOR #####################################################################

[EDITOR]
VSCROLL		= Yes
HSCROLL		= No
KBDACCEL	= Yes
VIRTUAL		= No
TABSTOSPACE	= No
REPLACETOP	= No
PROMPTUNDO	= Yes
PADTABS		= No
MARKEOL		= No
DRAGBLOCKS	= Yes
COPYWITHOUT	= No
BACKSPACE	= No
OVERWRITE	= 0
SHOWREPLACE	= Yes
AUTOSPACE	= No
PASTEDONTMOVE	= No
REMOVEASCII0	= No
FONTHEIGHT	= -16
FONTWIDTH	= 0
FONTESCAPEMENT	= 0
FONTORIENTATION	= 0
FONTWEIGHT	= 700
FONTITALIC	= 0
FONTUNDERLINE	= 0
FONTSTRIKEOUT	= 0
FONTCHARSET	= 0
FONTOUTPREC	= 3
FONTCLIPPREC	= 2
FONTQUALITY	= 1
FONTPITCHFAMILY	= 49
FONTFACENAME	= Courier New

## INSPECT ####################################################################

[INSPECT]
STOPRAPID	= Yes
STOPHOLDER	= Yes
STOPSHOULDER	= Yes
STOPSHAFT	= Yes
SHOWTOOLDLG	= Yes
SHOWTOOLVECTOR	= Yes
TRACKTOOL	= No
LOOPSIM		= Yes
SHOWDOTS	= Yes
SOLIDSHADING	= Yes
HIGHLIGHT	= Yes
SOLIDQUALITY	= 3
SOLIDCOLORING	= Yes
SHOWHOLDER	= Yes
TOOLTRANS	= No
SHOWORIGIN	= 0
MAPPING		= 0
PRINTQUALITY	= 1
TOOLCOUNT	= 46
SHOWPLOTCTRL	= No
SHOWBOUNDING	= No
SHOWPLOTCTRLALL	= No
LASTSAVEINF	= Yes
TOOL000		= 2|0|0|||63|0|150|0|53|150|53|4282417407|
TOOL001		= 2|13|0|||0.2|0|2|0|4|2|1/2|4294949973|
TOOL002		= 2|0|1|||1|0|1.5|0|1/8|1.5|1/8|4294967295|
TOOL003		= 2|1|1|||1|0|1.5|0|1/8|1.5|1/8|4294967295|
TOOL004		= 2|2|1|||1|0|1.5|1/32|1/8|1.5|1/8|4294967295|
TOOL005		= 2|2|1|||2|0|2.5|1/32|1/8|3|1/8|4284824832|
TOOL006		= 2|0|1|||1|0|1.5|0|1/4|1.5|1/4|4294967295|
TOOL007		= 2|1|1|||1|0|1.5|0|1/4|1.5|1/4|4294967295|
TOOL008		= 2|2|1|||1|0|1.5|1/16|1/4|1.5|1/4|4294967295|
TOOL009		= 2|0|1|||1|0|1.5|0|3/8|1.5|3/8|4294967295|
TOOL010		= 2|1|1|||1|0|1.5|0|3/8|1.5|3/8|4294967295|
TOOL011		= 2|2|1|||1|0|1.5|3/32|3/8|1.5|3/8|4294967295|
TOOL012		= 2|2|1|||1|0|1.5|3/32|3/8|1.5|3/8|4294967295|
TOOL013		= 2|0|1|||1|0|1.5|0|1/2|1.5|1/2|4294967295|
TOOL014		= 2|1|1|||1|0|1.5|0|1/2|1.5|1/2|4294967295|
TOOL015		= 2|2|1|||1|0|1.5|1/8|1/2|1.5|1/2|4294967295|
TOOL016		= 2|0|1|||2|0|3|0|5/8|3|5/8|4294967295|
TOOL017		= 2|1|1|||2|0|3|0|5/8|3|5/8|4294967295|
TOOL018		= 2|2|1|||2|0|3|5/32|5/8|3|5/8|4294967295|
TOOL019		= 2|0|1|||2|0|3|0|3/4|3|3/4|4294967295|
TOOL020		= 2|1|1|||2|0|3|0|3/4|3|3/4|4294967295|
TOOL021		= 2|2|1|||2|0|3|3/16|3/4|3|3/4|4294967295|
TOOL022		= 2|0|1|||2|0|3|0|7/8|3|7/8|4294967295|
TOOL023		= 2|1|1|||2|0|3|0|7/8|3|7/8|4294967295|
TOOL024		= 2|2|1|||2|0|3|7/32|7/8|3|7/8|4294967295|
TOOL025		= 2|0|1|||2|0|3|0|1|3|1|4294967295|
TOOL026		= 2|1|1|||2|0|3|0|1|3|1|4294967295|
TOOL027		= 2|2|1|||2|0|3|1/4|1|3|1|4294967295|
TOOL028		= 2|0|1|||.5|0|0|0|2.0|4|1.5|4290146048|
TOOL029		= 2|0|1|||.5|0|.5|0|2|5|1|4282417407|
TOOL030		= 2|3|1|||1|10|1||1/2|2|1/2|4294967295|
TOOL031		= 2|4|1|||1|118|2||1/2|2|1/2|4294967295|
TOOL032		= 2|5|1|||1|118|2||1/2|2|1/2|4294967295|
TOOL033		= 2|6|1|||1|118|2||1/2|2|1/2|4294967295|
TOOL034		= 2|7|1|||3/2|0|2||1/2|2|1/2|4294967295|
TOOL035		= 2|8|1|||1/4||1/4||2|3|1|4294967295|
TOOL036		= 2|9|1|||1|120|1||1/2|2|1/2|4294967295|
TOOL037		= 2|10|1|||1|120|1||1/2|2|1/2|4294967295|
TOOL038		= 2|11|1|||1|120|1||1/2|2|1/2|4294967295|
TOOL039		= 2|12|1|||1/4||1/4||2|3|1|4294967295|
TOOL040		= 2|13|1|||0.2|0|2.0|0|1.575|2.0|1.575|4294967295|
TOOL041		= 2|13|1|||1/4||1/4||2|3|1|4294967295|
TOOL042		= 2|13|1||SDSSDS|0.0|50|.0.39|6/16|4|7|2|4294967295|
TOOL043		= 2|13|1|||7|0|7|0|4|7|2|4284824832|
TOOL044		= 2|13|1|||.39|0|.39|0|4|9|2|4294901760|
TOOL045		= 2|14|1|||1||1|1/8|1/2|3/2|1/2|4294967295|

## INSPECTCOLOR ###############################################################

[INSPECTCOLOR]
COL002		= 4292362047
COL024		= 3221287152
COL029		= 3773162981
COL031		= 3774808064
COL030		= 3774808064
COL032		= 3221291007
COL053		= 2147483647
COL059		= 4291303448
COL060		= 4279801112
COL061		= 4278227088
COL062		= 4286529343
COL075		= 4284193502
COL076		= 4278190302
COL078		= 4278190302
COL079		= 4278190302
COL080		= 4278190302
COL081		= 4290146048
COL000		= 4278190080
COL001		= 4280690214
COL003		= 4293026145
COL004		= 4293690757
COL005		= 4291375152
COL025		= 3773162981
COL026		= 4278235648
COL020		= 4284023013
COL021		= 4284081408
COL022		= 4279835135
COL023		= 4279847961
COL027		= 3204497343
COL028		= 2144862208
COL006		= 4289045925
COL007		= 4278190256
COL008		= 4278235136
COL009		= 4278235312
COL010		= 2772385599
COL011		= 2130706432
COL012		= 4283190348
COL013		= 4278190182
COL014		= 2783307237
COL015		= 2783307237
COL016		= 520159231
COL017		= 3204448256
COL018		= 1057030143
COL019		= 4278190080
COL033		= 3221291007
COL034		= 3221291007
COL035		= 3221291007
COL036		= 2143223808
COL037		= 2143223808
COL038		= 4278255360
COL039		= 4278190335
COL040		= 2771596083
COL041		= 1915958067
COL042		= 2352165683
COL043		= 1056997247
COL044		= 1056964608
COL045		= 1056997247
COL046		= 1056964608
COL047		= 4278190080
COL048		= 2147483647
COL049		= 3623878656
COL050		= 4278255360
COL051		= 4278190335
COL052		= 4278190080
COL054		= 654311423
COL055		= 3221225471
COL056		= 433641688
COL057		= 1711276032
COL058		= 3221225471
COL063		= 3204448256
COL064		= 1070340377
COL074		= 3858759679
COL077		= 4278190302
COL500		= 4292886592
COL501		= 4294967295
COL502		= 4290822336
COL503		= 4289769648
COL504		= 4278254592
COL505		= 4294967295
COL506		= 4278190335
COL507		= 4294967168
COL508		= 4293839305
COL509		= 4294934783

## PRINTERSETUP ###############################################################

[PRINTERSETUP]
FONTHEIGHT	= -16
FONTWIDTH	= 0
FONTESCAPEMENT	= 0
FONTORIENTATION	= 0
FONTWEIGHT	= 0
FONTITALIC	= 0
FONTUNDERLINE	= 0
FONTSTRIKEOUT	= 0
FONTCHARSET	= 0
FONTOUTPREC	= 3
FONTCLIPPREC	= 2
FONTQUALITY	= 1
FONTPITCHFAMILY	= 49
FONTFACENAME	= Courier New
MFONTHEIGHT	= -13
MFONTWIDTH	= 0
MFONTESCAPEMENT	= 0
MFONTORIENTATION= 0
MFONTWEIGHT	= 0
MFONTITALIC	= 0
MFONTUNDERLINE	= 0
MFONTSTRIKEOUT	= 0
MFONTCHARSET	= 0
MFONTOUTPREC	= 3
MFONTCLIPPREC	= 2
MFONTQUALITY	= 1
MFONTPITCHFAMILY= 49
MFONTFACENAME	= Courier New
RAW		= No
USECOLORS	= Yes
USESYNTAXCOLORS	= Yes
PRINTHEADER	= Yes
PRINTHEADERFIRST= Yes
PRINTFOOTER	= Yes
SENDFORMFEED	= No
FORMFEEDLAST	= No
ENDLESSPAPER	= No
PAPERWIDTH	= 78
PAPERHEIGHT	= 64
HEADLEFT	= %F
HEADCENTER	= 
HEADRIGHT	= %t / %d
FOOTLEFT	= %c
FOOTCENTER	= 
FOOTRIGHT	= %p / %P
LEFTMARGIN	= 2.00
LEFTMARGININCH	= No
RIGHTMARGIN	= 2.00
RIGHTMARGININCH	= No

## SEARCH #####################################################################

[SEARCH]
SEARCH00	= M4
SEARCH01	= G55
SEARCH02	= G54
SEARCH03	= %
SEARCH04	= G76
SEARCH05	= P11
SEARCH06	= M05
SEARCH07	= G28
SEARCH08	= W0.0
SEARCH09	= M24
SEARCH10	= T0222
SEARCH11	= X6.0162
SEARCH12	= G30
SEARCH13	= M3
SEARCH14	= G97
SEARCH15	= G0 G28 U0
SEARCHWHOLE	= No
SEARCHCASE	= Yes
SEARCHALL	= No
SEARCHSPECIAL	= -1

## REPLACE ####################################################################

[REPLACE]
REPLACEFROM00	= X
REPLACETO00	= U
REPLACEFROM01	= U
REPLACETO01	= X
REPLACEFROM02	= M5
REPLACETO02	= x
REPLACEFROM03	= M9
REPLACETO03	= W
REPLACEFROM04	= X6.
REPLACETO04	= S625
REPLACEFROM05	= X8.583
REPLACETO05	= M04
REPLACEFROM06	= u
REPLACETO06	= M4
REPLACEFROM07	= )
REPLACETO07	= G55
REPLACEFROM08	= G95M03S50
REPLACETO08	= F0.006
REPLACEFROM09	= W
REPLACETO09	= G54
REPLACEFROM10	= Z3.65
REPLACETO10	= F1600
REPLACEFROM11	= F0.050
REPLACETO11	= F1000
REPLACEFROM12	= M07
REPLACETO12	= F75
REPLACEFROM13	= M30
REPLACETO13	= F100
REPLACEFROM14	= X15.1414
REPLACETO14	= F2200
REPLACEFROM15	= Z1.000
REPLACETO15	= F40
REPLACEWHOLE	= 0
REPLACECASE	= 0
REPLACESELECTION= 0

## EXTCMD #####################################################################

[EXTCMD]
TITLE00		= 
OUTPUT00	= $PATH\$FILENOEXT.OUT
EXE00		= 
PARAM00		= ""$PATH\$FILE" "$OUTFILE""
TITLE01		= 
OUTPUT01	= $PATH\$FILENOEXT.OUT
EXE01		= 
PARAM01		= ""$PATH\$FILE" "$OUTFILE""
LESSTHAN	= 
GREATERTHAN	= 

## EXTCONVERT #################################################################

[EXTCONVERT]
ENABLED		= No
IGNOREEXT	= 
DELETEOUTPUT	= Yes

## EXTENSIONS #################################################################

[EXTENSIONS]
CURRENT		= NCL,ISO,NCF,NC,HH,HNC,H

## MAINWINDOWPOS ##############################################################

[MAINWINDOWPOS]
LEFT		= 906
TOP		= 89
WIDTH		= 630
HEIGHT		= 616

## LIMIT ######################################################################

[LIMIT]
ENABLED		= No

## LAST #######################################################################

[LAST]
DNCTOOLBAR	= 0
SELECTMACHINE	= 0
PRINTFROMPAGE	= 1
PRINTTOPAGE	= 9999
DNCSETUP	= 0

## INITIALSTATE ###############################################################

[INITIALSTATE]
MACHINE		= 113C1E3A

## TERMINAL ###################################################################

[TERMINAL]
SHOWTERM	= No
SHOWCRLF	= No

## ADJUSTSPEED ################################################################

[ADJUSTSPEED]
MIN		= 0.000
MAX		= 5000.000
SELECTION	= No
DIGITS		= 0
VALUE		= 100.000

## ADJUSTFEED #################################################################

[ADJUSTFEED]
MIN		= 0.000
MAX		= 5000.000
SELECTION	= No
DIGITS		= 0
VALUE		= 100.000

## SERIALPORTS ################################################################

[SERIALPORTS]
USER0		= 
PORTLIST0	= 

## MATHOPS ####################################################################

[MATHOPS]
OFFSET		= 
SELECTION	= No
ARCTYPE		= 0
DIGITS		= 3
STRIPTRAIL	= No
NONMODALXYZ	= No
USECOMMA	= No
DEFAULTG91	= No
ANGLE		= 0.000000
POINTX		= 0.000000
POINTY		= 0.000000
LESSTHAN	= 
GREATERTHAN	= 
POINTZ		= 0.000000
STRIPLEAD	= No

## SIMPLEMATH #################################################################

[SIMPLEMATH]
MIN		= -999999.000
MAX		= 999999.000
VALUE		= 100.000
OTHER		= 
CASE		= 0
MODE		= 0
DIGITS		= 3
PARAMS		= 58720256
SELECTION	= No
STRIPTRAIL	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No
STRIPLEAD	= No
KEEPDECI	= No

## RIGHTMARGIN ################################################################

[RIGHTMARGIN]
2.00		= 

## PROTOCOLS ##################################################################

[PROTOCOLS]
PROTOCOL000DLL	= C:\Users\105065583\Documents\CIMCOEdit5\Protocols\PStandardSerial.dll
PROTOCOL000DESC	= Standard serial protocol
PROTOCOL000NAME	= STANDARDSERIAL
PROTOCOL000TIME	= 1136796214
PROTOCOL000VER	= 51175
COUNT		= 1

## ADDREMSTR ##################################################################

[ADDREMSTR]
LASTREMMODE	= 0
LASTREMTEXT	= 
LASTREMMATCH	= 
LASTREMREGEXP	= No
LASTADDMODE	= 0
LASTADDTEXT	= 
LASTADDMATCH	= 
LASTADDREGEXP	= No
