
## INIFILEVERSION #############################################################

[INIFILEVERSION]
VERSION		= 200

## GLOBAL #####################################################################

[GLOBAL]
LANGUAGE	= us
LICENSENUM	= DEMO-DEMO-00-DEMO-00
LASTLANGUAGE	= us
ACTIVEMACHINE	= BFW

## LAST #######################################################################

[LAST]
DNCSETUP	= 0

## SERIALPORTS ################################################################

[SERIALPORTS]
USER0		= 
PORTLIST0	= 

## PROTOCOLS ##################################################################

[PROTOCOLS]
PROTOCOL000DLL	= C:\Users\105065583\Saved Games\Documents\CIMCOEdit5\Protocols\PStandardSerial.dll
PROTOCOL000DESC	= Standard serial protocol
PROTOCOL000NAME	= STANDARDSERIAL
PROTOCOL000TIME	= 1136796214
PROTOCOL000VER	= 51175
COUNT		= 1
